-------------------------------------------------------------------------------
-- Title       : FPGA – Nios V – Temperature Sensor Interface
-- Project     : SPI-Based Temperature Acquisition using ADT7301
-------------------------------------------------------------------------------
-- File        : fpga_niosv.vhd
-- Author      : Alexandre Magalhaes
-- Created     : October 26th, 2025
-- Last Update : October 26th, 2025
-- Platform    : Intel/Altera Cyclone V SoC FPGA Kit
-------------------------------------------------------------------------------
-- Description :
-- This VHDL module integrates an Nios V soft processor with an SPI interface
-- to communicate with the Analog Devices ADT7301 temperature sensor.
--
-- The system reads temperature data from the ADT7301 via the SPI bus and 
-- makes it available for further processing or display. The design is 
-- targeted for the Cyclone V SoC FPGA platform and serves as an example of 
-- sensor interfacing using soft-core processors and custom FPGA logic.
--
-- Key Features:
--   - SPI communication with ADT7301 temperature sensor
--   - Nios V soft processor integration
--   - Compatible with Intel Quartus Prime design flow
--   - Suitable for embedded control and monitoring applications
-------------------------------------------------------------------------------
-- Revision History :
--   Rev 1.0 - Initial release .................................. Oct 26, 2025
-------------------------------------------------------------------------------

-- Standard IEEE libraries for VHDL
library ieee;
use ieee.std_logic_1164.all;   	-- For std_logic and std_logic_vector types
use ieee.numeric_std.all;       -- For numeric operations on std_logic_vector

-------------------------------------------------------------------------------
-- Top-level entity declaration
-------------------------------------------------------------------------------
entity fpga_niosv is
port (
	-- SYSTEM CLOCK AND RESET
    iClock      	: in 	std_logic;  					-- 50 MHz system clock input
    inReset     	: in 	std_logic;  					-- Active-high system reset

	-- DDR3 MEMORY INTERFACE (NIOS V)
    DDR3_A        	: out   std_logic_vector(14 downto 0);  -- DDR3 address lines
    DDR3_BA       	: out   std_logic_vector(2 downto 0);   -- DDR3 bank address
    DDR3_CAS_n    	: out   std_logic_vector(0 downto 0);   -- Column address strobe (active low)
    DDR3_CKE      	: out   std_logic_vector(0 downto 0);   -- Clock enable
    DDR3_CK_n     	: out   std_logic_vector(0 downto 0);   -- Differential clock negative
    DDR3_CK_p     	: out   std_logic_vector(0 downto 0);   -- Differential clock positive
    DDR3_CS_n     	: out   std_logic_vector(0 downto 0);   -- Chip select (active low)
    DDR3_DM       	: out   std_logic_vector(3 downto 0);   -- Data mask for write operations
    DDR3_DQ       	: inout std_logic_vector(31 downto 0);  -- Data bus
    DDR3_DQS_n    	: inout std_logic_vector(3 downto 0);   -- Differential data strobe negative
    DDR3_DQS_p    	: inout std_logic_vector(3 downto 0);   -- Differential data strobe positive
    DDR3_ODT      	: out   std_logic_vector(0 downto 0);   -- On-die termination control
    DDR3_RAS_n    	: out   std_logic_vector(0 downto 0);   -- Row address strobe (active low)
    DDR3_RESET_n  	: out   std_logic;                      -- DDR3 reset (active low)
    DDR3_RZQ      	: in    std_logic;                      -- On-chip calibration resistor input
    DDR3_WE_n     	: out   std_logic_vector(0 downto 0);   -- Write enable (active low)

	-- TEMPERATURE SENSOR (ADT7301)
	TEMP_DIN		: in std_logic;   						-- SPI data input from sensor (MISO)
	TEMP_DOUT		: out std_logic;  						-- SPI data output to sensor (MOSI, optional for read-only operation)
	TEMP_SCLK		: out std_logic;  						-- SPI clock output
	TEMP_CS_n		: out std_logic   						-- SPI chip select (active low)
);
end entity;

-------------------------------------------------------------------------------
-- Architecture
-------------------------------------------------------------------------------
architecture bhv of fpga_niosv is 

-- Internal signals can be declared here if needed
-- Example: internal clocks, resets, or bus signals
-- signal internal_clock : std_logic;

-------------------------------------------------------------------------------
-- Component declaration for the Nios V soft processor
-- This represents the processor system generated by Platform Designer (Qsys)
-------------------------------------------------------------------------------
component niosv is
port (
	-- SYSTEM CLOCK AND RESET INPUTS
	clk_50m_clk       			: in  	std_logic := 'X';
	reset_50m_reset_n 			: in  	std_logic := 'X';

	-- DDR3 MEMORY INTERFACE
	memory_mem_a                : out   std_logic_vector(14 downto 0);
	memory_mem_ba               : out   std_logic_vector(2 downto 0);
	memory_mem_ck               : out   std_logic_vector(0 downto 0);
	memory_mem_ck_n             : out   std_logic_vector(0 downto 0);
	memory_mem_cke              : out   std_logic_vector(0 downto 0);
	memory_mem_cs_n             : out   std_logic_vector(0 downto 0);
	memory_mem_dm               : out   std_logic_vector(3 downto 0);
	memory_mem_ras_n            : out   std_logic_vector(0 downto 0);
	memory_mem_cas_n            : out   std_logic_vector(0 downto 0);
	memory_mem_we_n             : out   std_logic_vector(0 downto 0);
	memory_mem_reset_n          : out   std_logic;
	memory_mem_dq               : inout std_logic_vector(31 downto 0) := (others => 'X');
	memory_mem_dqs              : inout std_logic_vector(3 downto 0)  := (others => 'X');
	memory_mem_dqs_n            : inout std_logic_vector(3 downto 0)  := (others => 'X');
	memory_mem_odt              : out   std_logic_vector(0 downto 0);
	oct_rzqin                   : in    std_logic := 'X';

	-- ADT7301 SPI INTERFACE
    adt7301_MISO                : in    std_logic := 'X';
    adt7301_MOSI                : out   std_logic;
    adt7301_SCLK                : out   std_logic;
    adt7301_SS_n                : out   std_logic
);
end component;

-------------------------------------------------------------------------------
-- Architecture body: instantiate Nios V processor and map top-level ports
-------------------------------------------------------------------------------
begin

-- Nios V processor instance
-- Connect top-level FPGA ports to the processor system
fpga_niosv_inst : component niosv
port map (

	-- SYSTEM CLOCK AND RESET
	clk_50m_clk       			=> iClock,
	reset_50m_reset_n 			=> inReset,

	-- DDR3 MEMORY INTERFACE
	memory_mem_a       			=> DDR3_A,
	memory_mem_ba      			=> DDR3_BA,
	memory_mem_ck      			=> DDR3_CK_p,
	memory_mem_ck_n    			=> DDR3_CK_n,
	memory_mem_cke     			=> DDR3_CKE,
	memory_mem_cs_n    			=> DDR3_CS_n,
	memory_mem_dm      			=> DDR3_DM,
	memory_mem_ras_n   			=> DDR3_RAS_n,
	memory_mem_cas_n   			=> DDR3_CAS_n,
	memory_mem_we_n    			=> DDR3_WE_n,
	memory_mem_reset_n 			=> DDR3_RESET_n,
	memory_mem_dq      			=> DDR3_DQ,
	memory_mem_dqs     			=> DDR3_DQS_p,
	memory_mem_dqs_n   			=> DDR3_DQS_n,
	memory_mem_odt     			=> DDR3_ODT,
	oct_rzqin          			=> DDR3_RZQ,

	-- ADT7301 SPI INTERFACE
    adt7301_MISO                => TEMP_DIN,
    adt7301_MOSI                => TEMP_DOUT,
    adt7301_SCLK                => TEMP_SCLK,
    adt7301_SS_n                => TEMP_CS_n
);
        
-- Additional concurrent statements or processes for custom logic can be added here.
    
end architecture;

