-------------------------------------------------------------------------------
-- Title      : [Design Title, e.g., System Top Level]
-- Project    : [Project Name, e.g., Embedded Processor Projects]
-------------------------------------------------------------------------------
-- File       : fpga_niosv.vhd
-- Author     : Alexandre Magalhaes
-- Created    : September 29th, 2025
-- Last update: September 29th, 2025
-- Platform   : Intel/Altera Cyclone V
-------------------------------------------------------------------------------
-- Description:
-- This template serves as the top-level entity for an FPGA design.
-- It is responsible for:
-- 1. Defining the primary I/O ports (clocks, resets, external interfaces).
-- 2. Instantiating and connecting internal system components (e.g., Nios V,
--    peripherals, custom logic).
--
-------------------------------------------------------------------------------

-- Libraries
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Top-level entity for the FPGA system.
entity fpga_niosv is
port (

	-- SYSTEM
    iClock      	: in 	std_logic;
    inReset     	: in 	std_logic;

	-- DDR3 (NIOS)
	DDR3_A        	: out   std_logic_vector(14 downto 0);
	DDR3_BA       	: out   std_logic_vector(2 downto 0);
	DDR3_CAS_n    	: out   std_logic_vector(0 downto 0);
	DDR3_CKE      	: out   std_logic_vector(0 downto 0);
	DDR3_CK_n     	: out   std_logic_vector(0 downto 0);
	DDR3_CK_p     	: out   std_logic_vector(0 downto 0);
	DDR3_CS_n     	: out   std_logic_vector(0 downto 0);
	DDR3_DM       	: out   std_logic_vector(3 downto 0);
	DDR3_DQ       	: inout std_logic_vector(31 downto 0);
	DDR3_DQS_n    	: inout std_logic_vector(3 downto 0);
	DDR3_DQS_p    	: inout std_logic_vector(3 downto 0);
	DDR3_ODT      	: out   std_logic_vector(0 downto 0);
	DDR3_RAS_n    	: out   std_logic_vector(0 downto 0);
	DDR3_RESET_n  	: out   std_logic;
	DDR3_RZQ      	: in    std_logic;
	DDR3_WE_n     	: out   std_logic_vector(0 downto 0)

	-- IOs
	--iKey        	: in 	std_logic;
    --oLed        	: out 	std_logic
);
end entity;

architecture bhv of fpga_niosv is 

-- Internal signal declarations (e.g., clocks, resets, bus connections)
-- signal internal_clock : std_logic;

-- Component declaration for the Nios V processor.
-- This component represents the design generated by Platform Designer (Qsys).
component niosv is
port (
	-- SYSTEM (Clocks and Resets)
	clk_50m_clk       			: in  	std_logic := 'X'; 	-- System Clock
	reset_50m_reset_n 			: in  	std_logic := 'X';	-- Active-low Reset

	-- DDR3 Interface
	memory_mem_a                : out   std_logic_vector(14 downto 0);
	memory_mem_ba               : out   std_logic_vector(2 downto 0);
	memory_mem_ck               : out   std_logic_vector(0 downto 0);
	memory_mem_ck_n             : out   std_logic_vector(0 downto 0);
	memory_mem_cke              : out   std_logic_vector(0 downto 0);
	memory_mem_cs_n             : out   std_logic_vector(0 downto 0);
	memory_mem_dm               : out   std_logic_vector(3 downto 0);
	memory_mem_ras_n            : out   std_logic_vector(0 downto 0);
	memory_mem_cas_n            : out   std_logic_vector(0 downto 0);
	memory_mem_we_n             : out   std_logic_vector(0 downto 0);
	memory_mem_reset_n          : out   std_logic;
	memory_mem_dq               : inout std_logic_vector(31 downto 0) := (others => 'X');
	memory_mem_dqs              : inout std_logic_vector(3 downto 0)  := (others => 'X');
	memory_mem_dqs_n            : inout std_logic_vector(3 downto 0)  := (others => 'X');
	memory_mem_odt              : out   std_logic_vector(0 downto 0);
	oct_rzqin                   : in    std_logic := 'X';

	-- PERIPHERALS
	key_export        			: in  	std_logic := 'X'; 	-- Key input to the Nios V system
	led_export        			: out 	std_logic        	-- LED output from the Nios V system
);
end component niosv;

begin

-- Instance of the Nios V processor component.
-- Map the top-level ports to the internal component ports.
fpga_niosv_inst : component niosv
port map (

	-- SYSTEM (Clocks and Resets)
	clk_50m_clk       			=> iClock,
	reset_50m_reset_n 			=> inReset,

	--DDR3
	memory_mem_a       			=> DDR3_A,
	memory_mem_ba      			=> DDR3_BA,
	memory_mem_ck      			=> DDR3_CK_p,
	memory_mem_ck_n    			=> DDR3_CK_n,
	memory_mem_cke     			=> DDR3_CKE,
	memory_mem_cs_n    			=> DDR3_CS_n,
	memory_mem_dm      			=> DDR3_DM,
	memory_mem_ras_n   			=> DDR3_RAS_n,
	memory_mem_cas_n   			=> DDR3_CAS_n,
	memory_mem_we_n    			=> DDR3_WE_n,
	memory_mem_reset_n 			=> DDR3_RESET_n,
	memory_mem_dq      			=> DDR3_DQ,
	memory_mem_dqs     			=> DDR3_DQS_p,
	memory_mem_dqs_n   			=> DDR3_DQS_n,
	memory_mem_odt     			=> DDR3_ODT,
	oct_rzqin          			=> DDR3_RZQ,

	-- PERIPHERALS
	key_export        			=> '0',
	led_export        			=> open
);
        
-- Additional concurrent statements or processes for custom logic can be added here.
    
end architecture;

